// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vocfzqveifedbvuhimwu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZvY2Z6cXZlaWZlZGJ2dWhpbXd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NDgwNTYsImV4cCI6MjA2NTIyNDA1Nn0.nvDJxJ8sL0n6bx7D7DoQG27Wq99hBs-HLQ0MWuNIO7w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);